In [151]:
import pandas as pd

## Les catégories d'emploi

In [152]:
#Lire le fichier excel
file = pd.ExcelFile('../Raw_data/Categorie/T205.xlsx')
file

In [153]:
#Obtenir les nom des feuille
sheets = file.sheet_names
sheets

['E - T15',
 'E - T25',
 'E - T50',
 'E - T',
 'H - T15',
 'H - T25',
 'H - T50',
 'H - T',
 'F - T15',
 'F - T25',
 'F - T50',
 'F - T']

In [154]:
#Obtenir les données d'un feuille comme un dataframe
df = file.parse('E - T15')
df

,"T205 : Emploi et part dans l'emploi selon la catégorie socioprofessionnelle, par sexe et âge regroupé, en moyenne annuelle",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,SEXE : Ensemble,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AGEREG : 15 - 24 ans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Catégorie socioprofessionnelle agrégée en 9 mo...,Agriculteurs exploitants,NaN,"Artisans, commerçants et chefs d'entreprises",NaN,Cadres et professions intellectuelles supérieures,NaN,Professions intermédiaires,NaN,Employés qualifiés,...,Employés non qualifiés,NaN,Ouvriers qualifiés,NaN,Ouvriers non qualifiés,NaN,"Autres (militaires du contingent, non renseigné)",NaN,Ensemble,NaN
4,Indicateurs,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...
5,Année,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1982,117,3,71,1.8,13,0.3,486,12.5,762,...,543,13.9,509,13.1,1031,26.5,360,9.3,3892,100
7,1983,122,3.2,63,1.7,14,0.4,483,12.7,741,...,531,13.9,461,12.1,1044,27.4,359,9.4,3818,100
8,1984,128,3.6,68,1.9,10,0.3,466,13.1,707,...,509,14.3,407,11.4,932,26.1,338,9.5,3565,100
9,1985,117,3.3,61,1.7,9,0.3,459,13,697,...,534,15.1,391,11.1,922,26.1,343,9.7,3533,100
10,1986,109,3.1,70,2,26,0.7,470,13.3,676,...,584,16.5,386,10.9,874,24.6,352,9.9,3545,100
11,1987,109,3.1,65,1.9,18,0.5,476,13.6,662,...,599,17.1,376,10.7,878,25,325,9.3,3508,100
12,1988,95,2.8,72,2.1,19,0.6,432,12.8,642,...,575,17.1,356,10.6,826,24.6,345,10.3,3362,100
13,1989,80,2.4,58,1.7,25,0.8,442,13.2,639,...,581,17.4,362,10.8,839,25.1,319,9.5,3345,100
14,1990,68,2.1,64,2,29,0.9,417,13.1,609,...,540,17,368,11.5,788,24.7,303,9.5,3185,100
15,1991,61,2.1,54,1.9,28,1,408,14,554,...,467,16.1,381,13.1,649,22.3,306,10.5,2908,100
16,1992,49,1.8,43,1.6,32,1.1,415,15,521,...,433,15.6,364,13.1,606,21.9,306,11.1,2768,100
17,1993,42,1.7,41,1.6,40,1.6,406,15.9,456,...,467,18.3,297,11.6,524,20.5,279,10.9,2553,100
18,1994,41,1.7,38,1.6,29,1.2,336,14.3,429,...,446,19,272,11.5,491,20.8,271,11.5,2354,100
19,1995,37,1.6,37,1.6,39,1.7,327,14,398,...,457,19.5,235,10,541,23.1,270,11.5,2341,100
20,1996,34,1.5,30,1.3,24,1.1,321,14.2,362,...,453,20.1,238,10.6,523,23.2,272,12.1,2258,100
21,1997,34,1.6,31,1.4,37,1.7,301,14.1,339,...,428,20.1,211,9.9,510,23.9,240,11.3,2131,100
22,1998,23,1.1,31,1.5,39,1.8,323,15,312,...,437,20.3,228,10.6,540,25.1,217,10.1,2151,100
23,1999,24,1.1,28,1.3,37,1.7,356,16.5,334,...,448,20.8,246,11.4,528,24.5,153,7.1,2155,100
24,2000,23,1,30,1.3,46,2,419,17.9,382,...,466,19.9,277,11.8,575,24.5,129,5.5,2348,100
25,2001,20,0.8,28,1.2,58,2.4,433,18.2,415,...,450,18.9,315,13.2,588,24.7,73,3.1,2380,100
26,2002,17,0.7,25,1,64,2.6,441,18.3,483,...,451,18.7,320,13.3,559,23.1,55,2.3,2416,100
27,2003,20,0.9,24,1,79,3.4,422,17.9,495,...,417,17.7,407,17.2,485,20.5,12,0.5,2361,100
28,2004,13,0.6,23,1,80,3.4,432,18.4,485,...,425,18.2,363,15.5,509,21.7,10,0.4,2340,100
29,2005,14,0.6,21,0.9,91,3.9,418,17.9,499,...,403,17.3,365,15.7,509,21.8,12,0.5,2331,100
30,2006,13,0.6,22,1,99,4.3,415,18,453,...,415,18,405,17.6,468,20.4,11,0.5,2301,100
31,2007,12,0.5,26,1.1,99,4.1,427,17.9,482,...,431,18.1,400,16.8,496,20.8,12,0.5,2383,100
32,2008,13,0.5,35,1.4,105,4.4,459,19.2,493,...,427,17.9,386,16.1,461,19.3,13,0.5,2390,100
33,2009,13,0.6,29,1.3,101,4.4,454,19.7,450,...,457,19.8,375,16.3,417,18.1,11,0.5,2307,100
34,2010,15,0.7,33,1.5,100,4.4,465,20.5,426,...,441,19.4,353,15.6,426,18.8,10,0.5,2270,100
35,2011,10,0.5,36,1.6,105,4.8,427,19.3,405,...,447,20.2,359,16.2,414,18.7,10,0.4,2214,100
36,2012,12,0.6,32,1.5,104,4.9,452,21.2,394,...,417,19.6,334,15.7,372,17.5,9,0.4,2126,100
37,2013,9,0.4,28,1.3,102,4.8,461,21.9,387,...,434,20.6,331,15.7,344,16.4,9,0.4,2105,100
38,2014,7,0.4,26,1.2,98,4.7,452,21.8,398,...,431,20.8,345,16.6,309,14.9,8,0.4,2074,100
39,2015,7,0.4,22,1,111,5.3,471,22.3,377,...,453,21.5,311,14.8,344,16.3,10,0.5,2107,100
40,2016,10,0.5,28,1.3,101,4.8,469,22.2,366,...,440,20.9,316,15,367,17.4,12,0.6,2110,100
41,2017,9,0.4,25,1.1,117,5.4,489,22.5,381,...,438,20.1,326,15,378,17.4,11,0.5,2174,100
42,2018,8,0.4,29,1.3,131,5.8,536,23.7,394,...,444,19.6,340,15,367,16.2,12,0.5,2261,100
43,2019,5,0.2,31,1.4,144,6.3,539,23.8,413,...,438,19.3,340,15,349,15.4,10,0.4,2268,100
44,2020,8,0.4,33,1.5,159,7.2,538,24.5,370,...,430,19.5,313,14.2,341,15.5,8,0.4,2201,100
45,"Note : données de 1982 à 2020, corrigées pour ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,"Champ : France hors Mayotte, population des mé...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,"Source : Insee, enquêtes Emploi (calculs Insee)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [155]:
#Enlever les lignes unutils
df.drop(labels=[0,1,2,5,45,46,47],inplace=True)
df

,"T205 : Emploi et part dans l'emploi selon la catégorie socioprofessionnelle, par sexe et âge regroupé, en moyenne annuelle",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
3,Catégorie socioprofessionnelle agrégée en 9 mo...,Agriculteurs exploitants,NaN,"Artisans, commerçants et chefs d'entreprises",NaN,Cadres et professions intellectuelles supérieures,NaN,Professions intermédiaires,NaN,Employés qualifiés,...,Employés non qualifiés,NaN,Ouvriers qualifiés,NaN,Ouvriers non qualifiés,NaN,"Autres (militaires du contingent, non renseigné)",NaN,Ensemble,NaN
4,Indicateurs,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...,Nombre d'emplois au sens du BIT (en milliers),Part dans l'emploi au sens du BIT (en pourcent...
6,1982,117,3,71,1.8,13,0.3,486,12.5,762,...,543,13.9,509,13.1,1031,26.5,360,9.3,3892,100
7,1983,122,3.2,63,1.7,14,0.4,483,12.7,741,...,531,13.9,461,12.1,1044,27.4,359,9.4,3818,100
8,1984,128,3.6,68,1.9,10,0.3,466,13.1,707,...,509,14.3,407,11.4,932,26.1,338,9.5,3565,100
9,1985,117,3.3,61,1.7,9,0.3,459,13,697,...,534,15.1,391,11.1,922,26.1,343,9.7,3533,100
10,1986,109,3.1,70,2,26,0.7,470,13.3,676,...,584,16.5,386,10.9,874,24.6,352,9.9,3545,100
11,1987,109,3.1,65,1.9,18,0.5,476,13.6,662,...,599,17.1,376,10.7,878,25,325,9.3,3508,100
12,1988,95,2.8,72,2.1,19,0.6,432,12.8,642,...,575,17.1,356,10.6,826,24.6,345,10.3,3362,100
13,1989,80,2.4,58,1.7,25,0.8,442,13.2,639,...,581,17.4,362,10.8,839,25.1,319,9.5,3345,100
14,1990,68,2.1,64,2,29,0.9,417,13.1,609,...,540,17,368,11.5,788,24.7,303,9.5,3185,100
15,1991,61,2.1,54,1.9,28,1,408,14,554,...,467,16.1,381,13.1,649,22.3,306,10.5,2908,100
16,1992,49,1.8,43,1.6,32,1.1,415,15,521,...,433,15.6,364,13.1,606,21.9,306,11.1,2768,100
17,1993,42,1.7,41,1.6,40,1.6,406,15.9,456,...,467,18.3,297,11.6,524,20.5,279,10.9,2553,100
18,1994,41,1.7,38,1.6,29,1.2,336,14.3,429,...,446,19,272,11.5,491,20.8,271,11.5,2354,100
19,1995,37,1.6,37,1.6,39,1.7,327,14,398,...,457,19.5,235,10,541,23.1,270,11.5,2341,100
20,1996,34,1.5,30,1.3,24,1.1,321,14.2,362,...,453,20.1,238,10.6,523,23.2,272,12.1,2258,100
21,1997,34,1.6,31,1.4,37,1.7,301,14.1,339,...,428,20.1,211,9.9,510,23.9,240,11.3,2131,100
22,1998,23,1.1,31,1.5,39,1.8,323,15,312,...,437,20.3,228,10.6,540,25.1,217,10.1,2151,100
23,1999,24,1.1,28,1.3,37,1.7,356,16.5,334,...,448,20.8,246,11.4,528,24.5,153,7.1,2155,100
24,2000,23,1,30,1.3,46,2,419,17.9,382,...,466,19.9,277,11.8,575,24.5,129,5.5,2348,100
25,2001,20,0.8,28,1.2,58,2.4,433,18.2,415,...,450,18.9,315,13.2,588,24.7,73,3.1,2380,100
26,2002,17,0.7,25,1,64,2.6,441,18.3,483,...,451,18.7,320,13.3,559,23.1,55,2.3,2416,100
27,2003,20,0.9,24,1,79,3.4,422,17.9,495,...,417,17.7,407,17.2,485,20.5,12,0.5,2361,100
28,2004,13,0.6,23,1,80,3.4,432,18.4,485,...,425,18.2,363,15.5,509,21.7,10,0.4,2340,100
29,2005,14,0.6,21,0.9,91,3.9,418,17.9,499,...,403,17.3,365,15.7,509,21.8,12,0.5,2331,100
30,2006,13,0.6,22,1,99,4.3,415,18,453,...,415,18,405,17.6,468,20.4,11,0.5,2301,100
31,2007,12,0.5,26,1.1,99,4.1,427,17.9,482,...,431,18.1,400,16.8,496,20.8,12,0.5,2383,100
32,2008,13,0.5,35,1.4,105,4.4,459,19.2,493,...,427,17.9,386,16.1,461,19.3,13,0.5,2390,100
33,2009,13,0.6,29,1.3,101,4.4,454,19.7,450,...,457,19.8,375,16.3,417,18.1,11,0.5,2307,100
34,2010,15,0.7,33,1.5,100,4.4,465,20.5,426,...,441,19.4,353,15.6,426,18.8,10,0.5,2270,100
35,2011,10,0.5,36,1.6,105,4.8,427,19.3,405,...,447,20.2,359,16.2,414,18.7,10,0.4,2214,100
36,2012,12,0.6,32,1.5,104,4.9,452,21.2,394,...,417,19.6,334,15.7,372,17.5,9,0.4,2126,100
37,2013,9,0.4,28,1.3,102,4.8,461,21.9,387,...,434,20.6,331,15.7,344,16.4,9,0.4,2105,100
38,2014,7,0.4,26,1.2,98,4.7,452,21.8,398,...,431,20.8,345,16.6,309,14.9,8,0.4,2074,100
39,2015,7,0.4,22,1,111,5.3,471,22.3,377,...,453,21.5,311,14.8,344,16.3,10,0.5,2107,100
40,2016,10,0.5,28,1.3,101,4.8,469,22.2,366,...,440,20.9,316,15,367,17.4,12,0.6,2110,100
41,2017,9,0.4,25,1.1,117,5.4,489,22.5,381,...,438,20.1,326,15,378,17.4,11,0.5,2174,100
42,2018,8,0.4,29,1.3,131,5.8,536,23.7,394,...,444,19.6,340,15,367,16.2,12,0.5,2261,100
43,2019,5,0.2,31,1.4,144,6.3,539,23.8,413,...,438,19.3,340,15,349,15.4,10,0.4,2268,100
44,2020,8,0.4,33,1.5,159,7.2,538,24.5,370,...,430,19.5,313,14.2,341,15.5,8,0.4,2201,100

In [156]:
#Enlever les columns unutils
df.dropna(axis=1,how='any',inplace=True)
df

,"T205 : Emploi et part dans l'emploi selon la catégorie socioprofessionnelle, par sexe et âge regroupé, en moyenne annuelle",Unnamed: 1,Unnamed: 3,Unnamed: 5,Unnamed: 7,Unnamed: 9,Unnamed: 11,Unnamed: 13,Unnamed: 15,Unnamed: 17,Unnamed: 19
3,Catégorie socioprofessionnelle agrégée en 9 mo...,Agriculteurs exploitants,"Artisans, commerçants et chefs d'entreprises",Cadres et professions intellectuelles supérieures,Professions intermédiaires,Employés qualifiés,Employés non qualifiés,Ouvriers qualifiés,Ouvriers non qualifiés,"Autres (militaires du contingent, non renseigné)",Ensemble
4,Indicateurs,Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers),Nombre d'emplois au sens du BIT (en milliers)
6,1982,117,71,13,486,762,543,509,1031,360,3892
7,1983,122,63,14,483,741,531,461,1044,359,3818
8,1984,128,68,10,466,707,509,407,932,338,3565
9,1985,117,61,9,459,697,534,391,922,343,3533
10,1986,109,70,26,470,676,584,386,874,352,3545
11,1987,109,65,18,476,662,599,376,878,325,3508
12,1988,95,72,19,432,642,575,356,826,345,3362
13,1989,80,58,25,442,639,581,362,839,319,3345
14,1990,68,64,29,417,609,540,368,788,303,3185
15,1991,61,54,28,408,554,467,381,649,306,2908
16,1992,49,43,32,415,521,433,364,606,306,2768
17,1993,42,41,40,406,456,467,297,524,279,2553
18,1994,41,38,29,336,429,446,272,491,271,2354
19,1995,37,37,39,327,398,457,235,541,270,2341
20,1996,34,30,24,321,362,453,238,523,272,2258
21,1997,34,31,37,301,339,428,211,510,240,2131
22,1998,23,31,39,323,312,437,228,540,217,2151
23,1999,24,28,37,356,334,448,246,528,153,2155
24,2000,23,30,46,419,382,466,277,575,129,2348
25,2001,20,28,58,433,415,450,315,588,73,2380
26,2002,17,25,64,441,483,451,320,559,55,2416
27,2003,20,24,79,422,495,417,407,485,12,2361
28,2004,13,23,80,432,485,425,363,509,10,2340
29,2005,14,21,91,418,499,403,365,509,12,2331
30,2006,13,22,99,415,453,415,405,468,11,2301
31,2007,12,26,99,427,482,431,400,496,12,2383
32,2008,13,35,105,459,493,427,386,461,13,2390
33,2009,13,29,101,454,450,457,375,417,11,2307
34,2010,15,33,100,465,426,441,353,426,10,2270
35,2011,10,36,105,427,405,447,359,414,10,2214
36,2012,12,32,104,452,394,417,334,372,9,2126
37,2013,9,28,102,461,387,434,331,344,9,2105
38,2014,7,26,98,452,398,431,345,309,8,2074
39,2015,7,22,111,471,377,453,311,344,10,2107
40,2016,10,28,101,469,366,440,316,367,12,2110
41,2017,9,25,117,489,381,438,326,378,11,2174
42,2018,8,29,131,536,394,444,340,367,12,2261
43,2019,5,31,144,539,413,438,340,349,10,2268
44,2020,8,33,159,538,370,430,313,341,8,2201

In [157]:
#Donner les nom des colonnes
labels = df.iloc[0]
df.drop(labels=[3,4], inplace = True)
df

,"T205 : Emploi et part dans l'emploi selon la catégorie socioprofessionnelle, par sexe et âge regroupé, en moyenne annuelle",Unnamed: 1,Unnamed: 3,Unnamed: 5,Unnamed: 7,Unnamed: 9,Unnamed: 11,Unnamed: 13,Unnamed: 15,Unnamed: 17,Unnamed: 19
6,1982,117,71,13,486,762,543,509,1031,360,3892
7,1983,122,63,14,483,741,531,461,1044,359,3818
8,1984,128,68,10,466,707,509,407,932,338,3565
9,1985,117,61,9,459,697,534,391,922,343,3533
10,1986,109,70,26,470,676,584,386,874,352,3545
11,1987,109,65,18,476,662,599,376,878,325,3508
12,1988,95,72,19,432,642,575,356,826,345,3362
13,1989,80,58,25,442,639,581,362,839,319,3345
14,1990,68,64,29,417,609,540,368,788,303,3185
15,1991,61,54,28,408,554,467,381,649,306,2908
16,1992,49,43,32,415,521,433,364,606,306,2768
17,1993,42,41,40,406,456,467,297,524,279,2553
18,1994,41,38,29,336,429,446,272,491,271,2354
19,1995,37,37,39,327,398,457,235,541,270,2341
20,1996,34,30,24,321,362,453,238,523,272,2258
21,1997,34,31,37,301,339,428,211,510,240,2131
22,1998,23,31,39,323,312,437,228,540,217,2151
23,1999,24,28,37,356,334,448,246,528,153,2155
24,2000,23,30,46,419,382,466,277,575,129,2348
25,2001,20,28,58,433,415,450,315,588,73,2380
26,2002,17,25,64,441,483,451,320,559,55,2416
27,2003,20,24,79,422,495,417,407,485,12,2361
28,2004,13,23,80,432,485,425,363,509,10,2340
29,2005,14,21,91,418,499,403,365,509,12,2331
30,2006,13,22,99,415,453,415,405,468,11,2301
31,2007,12,26,99,427,482,431,400,496,12,2383
32,2008,13,35,105,459,493,427,386,461,13,2390
33,2009,13,29,101,454,450,457,375,417,11,2307
34,2010,15,33,100,465,426,441,353,426,10,2270
35,2011,10,36,105,427,405,447,359,414,10,2214
36,2012,12,32,104,452,394,417,334,372,9,2126
37,2013,9,28,102,461,387,434,331,344,9,2105
38,2014,7,26,98,452,398,431,345,309,8,2074
39,2015,7,22,111,471,377,453,311,344,10,2107
40,2016,10,28,101,469,366,440,316,367,12,2110
41,2017,9,25,117,489,381,438,326,378,11,2174
42,2018,8,29,131,536,394,444,340,367,12,2261
43,2019,5,31,144,539,413,438,340,349,10,2268
44,2020,8,33,159,538,370,430,313,341,8,2201

In [158]:
#Renommer les colonnes
df.columns = labels
df

3,Catégorie socioprofessionnelle agrégée en 9 modalités,Agriculteurs exploitants,"Artisans, commerçants et chefs d'entreprises",Cadres et professions intellectuelles supérieures,Professions intermédiaires,Employés qualifiés,Employés non qualifiés,Ouvriers qualifiés,Ouvriers non qualifiés,"Autres (militaires du contingent, non renseigné)",Ensemble
6,1982,117,71,13,486,762,543,509,1031,360,3892
7,1983,122,63,14,483,741,531,461,1044,359,3818
8,1984,128,68,10,466,707,509,407,932,338,3565
9,1985,117,61,9,459,697,534,391,922,343,3533
10,1986,109,70,26,470,676,584,386,874,352,3545
11,1987,109,65,18,476,662,599,376,878,325,3508
12,1988,95,72,19,432,642,575,356,826,345,3362
13,1989,80,58,25,442,639,581,362,839,319,3345
14,1990,68,64,29,417,609,540,368,788,303,3185
15,1991,61,54,28,408,554,467,381,649,306,2908
16,1992,49,43,32,415,521,433,364,606,306,2768
17,1993,42,41,40,406,456,467,297,524,279,2553
18,1994,41,38,29,336,429,446,272,491,271,2354
19,1995,37,37,39,327,398,457,235,541,270,2341
20,1996,34,30,24,321,362,453,238,523,272,2258
21,1997,34,31,37,301,339,428,211,510,240,2131
22,1998,23,31,39,323,312,437,228,540,217,2151
23,1999,24,28,37,356,334,448,246,528,153,2155
24,2000,23,30,46,419,382,466,277,575,129,2348
25,2001,20,28,58,433,415,450,315,588,73,2380
26,2002,17,25,64,441,483,451,320,559,55,2416
27,2003,20,24,79,422,495,417,407,485,12,2361
28,2004,13,23,80,432,485,425,363,509,10,2340
29,2005,14,21,91,418,499,403,365,509,12,2331
30,2006,13,22,99,415,453,415,405,468,11,2301
31,2007,12,26,99,427,482,431,400,496,12,2383
32,2008,13,35,105,459,493,427,386,461,13,2390
33,2009,13,29,101,454,450,457,375,417,11,2307
34,2010,15,33,100,465,426,441,353,426,10,2270
35,2011,10,36,105,427,405,447,359,414,10,2214
36,2012,12,32,104,452,394,417,334,372,9,2126
37,2013,9,28,102,461,387,434,331,344,9,2105
38,2014,7,26,98,452,398,431,345,309,8,2074
39,2015,7,22,111,471,377,453,311,344,10,2107
40,2016,10,28,101,469,366,440,316,367,12,2110
41,2017,9,25,117,489,381,438,326,378,11,2174
42,2018,8,29,131,536,394,444,340,367,12,2261
43,2019,5,31,144,539,413,438,340,349,10,2268
44,2020,8,33,159,538,370,430,313,341,8,2201

In [159]:
df.columns[0]

'Catégorie socioprofessionnelle agrégée en 9 modalités'

In [160]:
df.rename(columns = {df.columns[0]:"Année"},inplace = True)
df

3,Année,Agriculteurs exploitants,"Artisans, commerçants et chefs d'entreprises",Cadres et professions intellectuelles supérieures,Professions intermédiaires,Employés qualifiés,Employés non qualifiés,Ouvriers qualifiés,Ouvriers non qualifiés,"Autres (militaires du contingent, non renseigné)",Ensemble
6,1982,117,71,13,486,762,543,509,1031,360,3892
7,1983,122,63,14,483,741,531,461,1044,359,3818
8,1984,128,68,10,466,707,509,407,932,338,3565
9,1985,117,61,9,459,697,534,391,922,343,3533
10,1986,109,70,26,470,676,584,386,874,352,3545
11,1987,109,65,18,476,662,599,376,878,325,3508
12,1988,95,72,19,432,642,575,356,826,345,3362
13,1989,80,58,25,442,639,581,362,839,319,3345
14,1990,68,64,29,417,609,540,368,788,303,3185
15,1991,61,54,28,408,554,467,381,649,306,2908
16,1992,49,43,32,415,521,433,364,606,306,2768
17,1993,42,41,40,406,456,467,297,524,279,2553
18,1994,41,38,29,336,429,446,272,491,271,2354
19,1995,37,37,39,327,398,457,235,541,270,2341
20,1996,34,30,24,321,362,453,238,523,272,2258
21,1997,34,31,37,301,339,428,211,510,240,2131
22,1998,23,31,39,323,312,437,228,540,217,2151
23,1999,24,28,37,356,334,448,246,528,153,2155
24,2000,23,30,46,419,382,466,277,575,129,2348
25,2001,20,28,58,433,415,450,315,588,73,2380
26,2002,17,25,64,441,483,451,320,559,55,2416
27,2003,20,24,79,422,495,417,407,485,12,2361
28,2004,13,23,80,432,485,425,363,509,10,2340
29,2005,14,21,91,418,499,403,365,509,12,2331
30,2006,13,22,99,415,453,415,405,468,11,2301
31,2007,12,26,99,427,482,431,400,496,12,2383
32,2008,13,35,105,459,493,427,386,461,13,2390
33,2009,13,29,101,454,450,457,375,417,11,2307
34,2010,15,33,100,465,426,441,353,426,10,2270
35,2011,10,36,105,427,405,447,359,414,10,2214
36,2012,12,32,104,452,394,417,334,372,9,2126
37,2013,9,28,102,461,387,434,331,344,9,2105
38,2014,7,26,98,452,398,431,345,309,8,2074
39,2015,7,22,111,471,377,453,311,344,10,2107
40,2016,10,28,101,469,366,440,316,367,12,2110
41,2017,9,25,117,489,381,438,326,378,11,2174
42,2018,8,29,131,536,394,444,340,367,12,2261
43,2019,5,31,144,539,413,438,340,349,10,2268
44,2020,8,33,159,538,370,430,313,341,8,2201

Toutes les feuilles dans ce fichier sont en meme format. Donc on utilise touts les étapes précent pour créer une fonction afin de faciliter la démarche de la préparation des données.

In [164]:
def separation_df(fichier, sheet):
    temp = fichier.parse(sheet)
    
    temp.drop(labels=[0,1,2,5,45,46,47],inplace=True)
    temp.dropna(axis=1,how='any',inplace=True)
    
    labels = temp.iloc[0]
    temp.drop(labels=[3,4], inplace = True)
    
    temp.columns = labels
    temp.rename(columns = {temp.columns[0]:"Année"},inplace = True)
    
    temp.reset_index()
    return temp

On utilise un boucle pour appliquer cette fonction au but d'obtenir un dataframe concatné avec touts les données

In [168]:
#Crétaion de variable pour le résultat final

res_fin = pd.DataFrame()
for i in range (0,len(sheets)):
    
    #Utilisation de la fonction
    temp = separation_df(file,sheets[i])
    
    #Ajouté les type de données (age et sexe)
    temp['new'] = sheets[i]
    
    #Concatener avec les données précedent
    res_fin = pd.concat([res_fin,temp])
    
res_fin

3,Année,Agriculteurs exploitants,"Artisans, commerçants et chefs d'entreprises",Cadres et professions intellectuelles supérieures,Professions intermédiaires,Employés qualifiés,Employés non qualifiés,Ouvriers qualifiés,Ouvriers non qualifiés,"Autres (militaires du contingent, non renseigné)",Ensemble,new
6,1982,117,71,13,486,762,543,509,1031,360,3892,E - T15
7,1983,122,63,14,483,741,531,461,1044,359,3818,E - T15
8,1984,128,68,10,466,707,509,407,932,338,3565,E - T15
9,1985,117,61,9,459,697,534,391,922,343,3533,E - T15
10,1986,109,70,26,470,676,584,386,874,352,3545,E - T15
...,...,...,...,...,...,...,...,...,...,...,...,...
40,2016,129,506,1917,3621,2788,2768,442,623,54,12848,F - T
41,2017,116,520,1966,3627,2762,2782,457,649,41,12921,F - T
42,2018,104,498,2052,3704,2829,2749,447,622,49,13053,F - T
43,2019,103,519,2213,3730,2814,2665,456,606,57,13163,F - T
44,2020,96,557,2342,3796,2721,2509,450,581,58,13110,F - T

In [169]:
id_vars = 
pd.melt(res_fin,value_vars = ,
       id_vars = ['Année','new'])

     Année      new                         3  value
0     1982  E - T15  Agriculteurs exploitants    117
1     1983  E - T15  Agriculteurs exploitants    122
2     1984  E - T15  Agriculteurs exploitants    128
3     1985  E - T15  Agriculteurs exploitants    117
4     1986  E - T15  Agriculteurs exploitants    109
...    ...      ...                       ...    ...
4675  2016    F - T                  Ensemble  12848
4676  2017    F - T                  Ensemble  12921
4677  2018    F - T                  Ensemble  13053
4678  2019    F - T                  Ensemble  13163
4679  2020    F - T                  Ensemble  13110

[4680 rows x 4 columns]

### Note: (Pour la table d'année) <br>
    Nous avons les données de categorie de 1982 jusqu'a 2020 ici.